apiVersion: v1
kind: Service
metadata:
  name: ds-catalog-backend
  labels:
    app: ds-catalog-backend
spec:
  type: ClusterIP
  selector:
    app: ds-catalog-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
