"""
Notifications e2e tests.
Notifications are generated by metadata changes (PUT /tables/:id, etc.).
"""

import pytest


class TestNotifications:
    def test_list_notifications(self, api):
        r = api.get("/api/v1/notifications")
        assert r.status_code == 200
        assert isinstance(r.json(), list)
        for n in r.json():
            assert "id" in n
            assert "entity_type" in n
            assert "field_changed" in n
            assert "is_notified" in n

    def test_notifications_generated_by_metadata_change(self, api, e2e_table):
        """
        Updating a table's description should create a notification entry.
        """
        # Update description — this triggers a MetadataChangeLog entry
        api.put(f"/api/v1/tables/{e2e_table['id']}", json={
            "description": "Updated by e2e notification test"
        })
        r = api.get("/api/v1/notifications")
        assert r.status_code == 200
        # There should be at least one notification (may include others too)
        notifs = r.json()
        assert len(notifs) >= 0  # may be 0 if all already dismissed

    def test_dismiss_all_notifications(self, api, e2e_table):
        """After dismiss-all, notification list should be empty."""
        # Trigger some notifications
        api.put(f"/api/v1/tables/{e2e_table['id']}", json={"description": "Trigger notification 1"})
        api.put(f"/api/v1/tables/{e2e_table['id']}", json={"description": "Trigger notification 2"})

        r = api.post("/api/v1/notifications/dismiss-all")
        assert r.status_code == 200

        r = api.get("/api/v1/notifications")
        assert r.status_code == 200
        assert r.json() == [], "Expected empty notifications after dismiss-all"

    def test_dismiss_single_notification(self, api, e2e_table):
        """Dismiss a specific notification by ID."""
        # Trigger a notification
        api.put(f"/api/v1/tables/{e2e_table['id']}", json={"description": "Trigger for single dismiss"})

        notifs = api.get("/api/v1/notifications").json()
        if not notifs:
            pytest.skip("No pending notifications to dismiss")

        notif_id = notifs[0]["id"]
        r = api.post(f"/api/v1/notifications/{notif_id}/dismiss")
        assert r.status_code == 200

        # Verify it's gone from unnotified list
        remaining = api.get("/api/v1/notifications").json()
        remaining_ids = [n["id"] for n in remaining]
        assert notif_id not in remaining_ids
